### ISSUE TITLE
add metallb to setup 

### ISSUE THREAD

**Issue by marcstreeter** [onedr0p/k3s-gitops-arm#12]
Noticed the graphic included the use of metallb but none of the documentation mention it.

**Comment by onedr0p** [comment]
What would you like to see? MetalLB will be deployed by Flux once you have that working.

There's a `@CHANGEME` tag on the deployment, which tells you to update the IP address range for MetalLB to use in your network.

https://github.com/onedr0p/k3s-gitops-arm/blob/master/deployments/kube-system/metallb/metallb.yaml
