### ISSUE TITLE
File not valid cloud-init 

### ISSUE THREAD

**Issue by xunholy** [onedr0p/k3s-gitops-arm#15]
Possibly due to newer versions of cloud-init.

Need to remove `---` from L1

L2 must match `#cloud-init` without the extra space padding after the `#`

https://github.com/onedr0p/k3s-gitops-arm/blob/06ce91f7a123f186b7801fb07cc77d733e5c10e9/setup/cloud-config.example.yml#L1

**Comment by onedr0p** [comment]
Fixed in
https://github.com/onedr0p/k3s-gitops-arm/commit/5852ed61bce0e011d66f6e81734953a7ce4308a2
