### ISSUE TITLE
Missing Namespace Manually Installing Flux

### ISSUE THREAD

**Issue by arranf** [onedr0p/k3s-gitops-arm#17]
I ran into an issue with the manual instructions for installing Flux and Helm.

(Below, `namespaces` in the name of the equivalent folder to your `deployments`) 
`helm upgrade --install flux --values namespaces/flux/flux/flux-values.yaml  --namespace flux     fluxcd/flux`

I had to manually `kubectl apply -f ./flux/namespace.yaml` and then the command would work.

**Comment by onedr0p** [comment]
Thanks for reporting, fixed in https://github.com/onedr0p/k3s-gitops-arm/commit/9fdcdfefe69df22fd05a5cd538e4a09cc2161d66
