### ISSUE TITLE
Conflicting CRD Manually Installing Helm Operator

### ISSUE THREAD

**Issue by arranf** [onedr0p/k3s-gitops-arm#18]
Manually installing Helm Operator produces this conflicting CRD.

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: helmreleases.helm.fluxcd.io, existing_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, new_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition`

Solution was to remove the `createCRD: true` from the `flux-helm-operator-values.yaml`

**Comment by onedr0p** [comment]
This seems to be an issue with helm3, which I use in this repo. I think helm2 requires `createCRD: true`.

Fixed in https://github.com/onedr0p/k3s-gitops-arm/commit/af6a3c91c194ef4cb60af24ebe3c79aad761c4b4
