### ISSUE TITLE
Ubuntu 20 and Userland changes

### ISSUE THREAD

**Issue by radum** [onedr0p/k3s-gitops-arm#19]
Hello,

First of all, thank you very much for this repo, it has saved me lots of hours and pain by learning from example. Really thank you.

I wanted to point out first that this will not work for Ubuntu 20 as k3s has an [https://github.com/rancher/k3s/issues/1712](issue) for now.

And 2nd I wanted to ask if PI userland patch still works. There have been some changes in that repo 2 days ago and the patch is failing.

Was wondering if you know why and how to fix it.

```
fatal: [192.168.0.100]: FAILED! => changed=true
  cmd: |-
    set -o pipefail
    echo /opt/vc/lib | tee /etc/ld.so.conf.d/00-vmcs.conf
  delta: '0:00:00.006693'
  end: '2020-05-30 23:38:15.220359'
  msg: non-zero return code
  rc: 2
  start: '2020-05-30 23:38:15.213666'
  stderr: '/bin/sh: 1: set: Illegal option -o pipefail'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
fatal: [192.168.0.101]: FAILED! => changed=true
  cmd: |-
    set -o pipefail
    echo /opt/vc/lib | tee /etc/ld.so.conf.d/00-vmcs.conf
  delta: '0:00:00.006634'
  end: '2020-05-30 23:38:15.312757'
  msg: non-zero return code
  rc: 2
  start: '2020-05-30 23:38:15.306123'
  stderr: '/bin/sh: 1: set: Illegal option -o pipefail'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
fatal: [192.168.0.102]: FAILED! => changed=true
  cmd: |-
    set -o pipefail
    echo /opt/vc/lib | tee /etc/ld.so.conf.d/00-vmcs.conf
  delta: '0:00:00.006775'
  end: '2020-05-30 23:38:15.418153'
  msg: non-zero return code
  rc: 2
  start: '2020-05-30 23:38:15.411378'
  stderr: '/bin/sh: 1: set: Illegal option -o pipefail'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**Comment by onedr0p** [comment]
I haven't had time to hack this with Ubuntu 20.04, not sure when I'll get to it to be honest. It would probably be best to remove the userland stuff and then go with your PR

**Comment by radum** [comment]
Yeah no worries, personally I don't really need userland and I removed it on my instance.

**Comment by onedr0p** [comment]
I have removed userland and went with your PR
