### ISSUE TITLE
Flux Helm Chart has been Updated; Instructions do not work

### ISSUE THREAD

**Issue by voigt** [onedr0p/k3s-gitops-arm#21]
Hi, first of all: thanks for the effort - helped a lot :)

I noticed, that the instructuion in [docsflux-helm-operator.md](https://github.com/onedr0p/k3s-gitops-arm/blob/master/docs/flux-helm-operator.md) are pulling the latest helm chart for flux.

This currently leads to a not starting flux container, as in flux helm-chart 1.3.0 an additional parameter (`ssh-keygen-format`) has been added, which is not present in flux 1.18.

**Not working:**
```
helm upgrade --install flux \
    --values deployments/flux/flux/flux-values.yaml \
    --namespace flux \
    fluxcd/flux
```

**Working:**
```
helm upgrade --install flux \
    --values deployments/flux/flux/flux-values.yaml \
    --version 1.2.0
    --namespace flux \
    fluxcd/flux
```

**Comment by onedr0p** [comment]
according to their docs `ssh-keygen-format` does have a default value. I haven't had time to experiment with latest versions of helm operator or flux on arm.
