### ISSUE TITLE
Investigate rook-ceph on arm64

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops-arm#4]

**Comment by dalekurt** [comment]
I'm currently trying to configure rook-ceph on my k3s cluster running on Raspberry Pi. The issue I've ran into with k3s having [issues](https://github.com/rancher/k3s/issues/1278) pulling multi-arch Docker images

**Comment by onedr0p** [comment]
Hi @dalekurt I haven't had any issue with pulling multi-arch images (yet), but for rook-ceph you can also follow this issue

https://github.com/billimek/k8s-gitops/issues/89

**Comment by serverbaboon** [comment]
If you disable the CSI drivers and enable the Flex driver you can later versions of Rook/Ceph, I have edited the Rook docs sample yamls to do this.

**Comment by brontide** [comment]
Neither ceph or edgefs appear to be functional on arm64 clusters at this time.

**Comment by serverbaboon** [comment]
You can get Rook/Ceph working if you stick to the Flex driver. Here is a sample set of Yaml files that will get it working. 

https://github.com/serverbaboon/rook-arm64

NB you will need to change to suit your config.

I have not updated for the latest release of Rook

**Comment by brontide** [comment]
@serverbaboon thanks for that.  Took a little playing with it and a lot of my own stupidity ( not clearing the local rook dirs between attempts ) but I finally took the current manifests and adapted them like yours and was able to get a working cluster up and running.
